name: C/C++ CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        python ./build_scripts/build_usd.py "C:\USD"
    - name: UploadMeta
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/
